send_keys:
  description: send keys.
  fields:
    me:
      description: Device me value
      example: '"0010"'
    agt:
      description: Smart Center AGT
      example: "_xXXXXXXXXXXXXXXXXX"
    ai:
      description: Remote control AI
      example: "AI_IR_xxxx_xxxxxxxx"
    category:
      description: Remote control device category
      example: "custom"
    brand:
      description: Remote control brand
      example: "custom"
    keys:
      description: Remote control command key
      example: '"[\"CS_1\"]"'

scene_set:
  description: Scene Set.
  fields:
    agt:
      description: Smart Center AGT
      example: "_xXXXXXXXXXXXXXXXXX"
    id:
      description: Message ID number
      example: "AIxxxxxxxxxxxx"
